# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: puvilink2025
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: payflow2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: DynamoDB-CRUD

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region : us-east-1

  iam:
    role:
      statements:
        - Effect : Allow
          Action:
            - dynamodb:Scan
            # - dynamodb:GetItem
            - dynamodb:PutItem
            # - dynamodb:UpdateItem
            # - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/Customers

# Functions
functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  
  # GET
  getCustomers:
    handler: handler.getCustomers
    events:
      - httpApi:
          path: /customers
          method: get
  
  # POST
  createCustomer:
    handler: handler.createCustomer
    events:
      - httpApi:
          path : /customers
          method : post 

  # # GET SPECIFIC
  # getCustomerById:
  #   handler: handler.getCustomerById
  #   events:
  #     - httpApi:
  #         path: /customers/{id}
  #         method: get
  
  # # UPDATE SPECIFIC
  # updateCustomer:
  #   handler: handler.updateCustomer
  #   events:
  #     - httpApi:
  #         path: /customers/{id}
  #         method: put

  # # DELETE SPECIFIC
  # deleteCustomer:
  #   handler: handler.deleteCustomer
  #   events:
  #     - httpApi:
  #         path: /customers/{id}
  #         method: delete

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH